# Generated by Django 5.0.7 on 2024-07-11 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Дата пробега:')),
                ('city', models.CharField(help_text='Город / нас.п.:', max_length=30)),
                ('distance', models.DecimalField(decimal_places=3, help_text='Дистанция, км:', max_digits=6)),
                ('price', models.PositiveSmallIntegerField(help_text='Стоимость, грн:')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='Псевдоним:', max_length=20, unique=True)),
                ('password', models.CharField(help_text='Пароль:', max_length=20)),
                ('email', models.EmailField(help_text='e-mail:', max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=3, help_text='Расстояние от Старта, км:', max_digits=6)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diplom.events')),
            ],
        ),
        migrations.CreateModel(
            name='AgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_do', models.PositiveSmallIntegerField(help_text='возраст до:')),
                ('category', models.CharField(help_text='Возрастная категория:', max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diplom.events')),
            ],
        ),
        migrations.CreateModel(
            name='Runners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fam', models.CharField(help_text='Фамилия:', max_length=20)),
                ('name', models.CharField(help_text='Имя:', max_length=20)),
                ('gender', models.CharField(choices=[('men', 'м'), ('women', 'ж')], db_index=True, help_text='Пол:', max_length=5)),
                ('birthday', models.DateField(help_text='Дата рождения:')),
                ('city', models.CharField(help_text='Город / нас.п.:', max_length=30)),
                ('tel', models.CharField(blank=True, help_text='Телефон:', max_length=20)),
                ('sportTeam', models.CharField(blank=True, help_text='Команда:', max_length=20)),
                ('identKod', models.BigIntegerField(help_text='Идент. код:', unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Diplom.users')),
            ],
        ),
    ]
