# Generated by Django 5.0.7 on 2024-07-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diplom', '0002_protokols'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protokols',
            name='finresult',
            field=models.TimeField(help_text='Финишный результат:'),
        ),
    ]
