# Generated by Django 5.0.7 on 2024-07-11 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diplom', '0003_alter_protokols_finresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TimeField(help_text='Результат на КП:')),
                ('check_point', models.ForeignKey(help_text='КП ', on_delete=django.db.models.deletion.CASCADE, to='Diplom.checkpoints')),
                ('protokol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diplom.protokols')),
            ],
        ),
    ]
