# Generated by Django 5.0.7 on 2024-07-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diplom', '0004_resultdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='beginNumber',
            field=models.PositiveIntegerField(default=1, help_text='№ участников, от:'),
        ),
        migrations.AddField(
            model_name='events',
            name='maxNumber',
            field=models.PositiveIntegerField(default=100, help_text='№ участников, дл:'),
        ),
        migrations.AddField(
            model_name='protokols',
            name='number',
            field=models.PositiveIntegerField(default=0, help_text='№ участника:'),
        ),
        migrations.DeleteModel(
            name='ResultDetail',
        ),
    ]
